DROP TABLE public.businesses CASCADE;
DROP TABLE public.users CASCADE;
DROP TABLE public.products CASCADE;
DROP TABLE public.customers CASCADE;
DROP TABLE public.categories CASCADE;
DROP TABLE public.order_details CASCADE;
DROP TABLE public.orders CASCADE;
DROP TABLE public.payment_methods CASCADE;
DROP TABLE public.shopping_carts CASCADE;