CREATE TABLE public.businesses (
    id smallint NOT NULL,
    code varchar(20) NOT NULL,
    name varchar(150) NOT NULL,
    description varchar(255) NOT NULL,
    email varchar(100) NOT NULL,
    address varchar(255) NOT NULL,
    city varchar(50) NOT NULL,
    country varchar(70) NOT NULL,
    logo_url varchar(255) NOT NULL,
    template text NOT NULL,
    use_template boolean NOT NULL,
    active boolean NOT NULL,
    creation_date timestamp with time zone NOT NULL,
    update_date timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.businesses
    ADD UNIQUE (code);

ALTER TABLE public.businesses
    ADD UNIQUE (name);

ALTER TABLE public.businesses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767);


CREATE TABLE public.users (
    id integer NOT NULL,
    business_id smallint NOT NULL,
    code varchar(20) NOT NULL,
    role varchar(20) NOT NULL,
    email varchar(100) NOT NULL,
    password varchar(255) NOT NULL,
    active boolean NOT NULL,
    creation_date timestamp with time zone NOT NULL,
    update_date timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.users
    ADD UNIQUE (code);

ALTER TABLE public.users
    ADD UNIQUE (business_id, email);

COMMENT ON COLUMN public.users.role
    IS 'ADMIN
CUSTOMER';    

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647);


CREATE TABLE public.products (
    id integer NOT NULL,
    business_id smallint NOT NULL,
    category_id integer NOT NULL,
    code varchar(20) NOT NULL,
    brand varchar(150) NOT NULL,
    name varchar(150) NOT NULL,
    description varchar(255) NOT NULL,
    tax numeric(8,2),
    discount numeric(8,2),
    price numeric(8,2) NOT NULL,
    stock integer NOT NULL,
    image_url varchar(255) NOT NULL,
    active boolean NOT NULL,
    creation_date timestamp with time zone NOT NULL,
    update_date timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.products
    ADD UNIQUE (code);

ALTER TABLE public.products
    ADD UNIQUE (business_id, category_id, name);

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647);


CREATE TABLE public.customers (
    id integer NOT NULL,
    user_id integer NOT NULL,
    business_id smallint NOT NULL,
    code varchar(20) NOT NULL,
    dni varchar(13) NOT NULL,
    first_name varchar(50) NOT NULL,
    last_name varchar(50) NOT NULL,
    phone varchar(15) NOT NULL,
    address varchar(255) NOT NULL,
    active boolean NOT NULL,
    creation_date timestamp with time zone NOT NULL,
    update_date timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.customers
    ADD UNIQUE (code);

ALTER TABLE public.customers
    ADD UNIQUE (business_id, dni);

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647);


CREATE TABLE public.categories (
    id integer NOT NULL,
    parent_id integer,
    business_id smallint NOT NULL,
    code varchar(20) NOT NULL,
    name varchar(150) NOT NULL,
    description varchar(255) NOT NULL,
    image_url varchar(255) NOT NULL,
    active boolean NOT NULL,
    creation_date timestamp with time zone NOT NULL,
    update_date timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.categories
    ADD UNIQUE (code);

ALTER TABLE public.categories
    ADD UNIQUE (business_id, name);

CREATE INDEX ON public.categories
    (parent_id);

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647);


CREATE TABLE public.order_details (
    id integer NOT NULL,
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(8,2) NOT NULL,
    total numeric(8,2) NOT NULL,
    sub_total numeric(8,2) NOT NULL,
    tax numeric(8,2) NOT NULL,
    discount numeric(8,2) NOT NULL,
    active boolean NOT NULL,
    creation_date timestamp with time zone NOT NULL,
    update_date timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.order_details
    ADD UNIQUE (order_id, product_id);

ALTER TABLE public.order_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647);


CREATE TABLE public.orders (
    id integer NOT NULL,
    business_id smallint NOT NULL,
    customer_id integer NOT NULL,
    payment_method_id smallint NOT NULL,
    status varchar(20) NOT NULL,
    date timestamp with time zone NOT NULL,
    total numeric(8,2) NOT NULL,
    sub_total numeric(8,2) NOT NULL,
    tax numeric(8,2) NOT NULL,
    discount numeric(8,2) NOT NULL,
    delivery_address varchar(255) NOT NULL,
    notes text,
    active boolean NOT NULL,
    creation_date timestamp with time zone NOT NULL,
    update_date timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX ON public.orders
    (business_id);
CREATE INDEX ON public.orders
    (customer_id);
CREATE INDEX ON public.orders
    (payment_method_id);


COMMENT ON COLUMN public.orders.status
    IS 'ACTIVE
CANCELLED
COMPLETED';

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647);


CREATE TABLE public.payment_methods (
    id smallint NOT NULL,
    business_id smallint NOT NULL,
    code varchar(20) NOT NULL,
    name varchar(100) NOT NULL,
    description varchar(255) NOT NULL,
    active boolean NOT NULL,
    creation_date timestamp with time zone NOT NULL,
    update_date timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.payment_methods
    ADD UNIQUE (code);

ALTER TABLE public.payment_methods
    ADD UNIQUE (business_id, name);

CREATE INDEX ON public.payment_methods
    (business_id);

ALTER TABLE public.payment_methods ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767);


CREATE TABLE public.shopping_carts (
    id integer NOT NULL,
    business_id smallint NOT NULL,
    customer_id integer NOT NULL,
    code varchar NOT NULL,
    payload JSONB NOT NULL,
    status varchar(20) NOT NULL,
    active boolean NOT NULL,
    creation_date timestamp with time zone NOT NULL,
    update_date timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX ON public.shopping_carts
    (business_id);
CREATE INDEX ON public.shopping_carts
    (customer_id);


COMMENT ON COLUMN public.shopping_carts.status
    IS 'ACTIVE
CANCELLED
COMPLETED';

ALTER TABLE public.shopping_carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647);


ALTER TABLE public.users ADD CONSTRAINT FK_users__business_id FOREIGN KEY (business_id) REFERENCES public.businesses(id);
ALTER TABLE public.products ADD CONSTRAINT FK_products__business_id FOREIGN KEY (business_id) REFERENCES public.businesses(id);
ALTER TABLE public.products ADD CONSTRAINT FK_products__category_id FOREIGN KEY (category_id) REFERENCES public.categories(id);
ALTER TABLE public.customers ADD CONSTRAINT FK_customers__user_id FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE public.customers ADD CONSTRAINT FK_customers__business_id FOREIGN KEY (business_id) REFERENCES public.businesses(id);
ALTER TABLE public.categories ADD CONSTRAINT FK_categories__parent_id FOREIGN KEY (parent_id) REFERENCES public.categories(id);
ALTER TABLE public.categories ADD CONSTRAINT FK_categories__business_id FOREIGN KEY (business_id) REFERENCES public.businesses(id);
ALTER TABLE public.order_details ADD CONSTRAINT FK_order_details__order_id FOREIGN KEY (order_id) REFERENCES public.orders(id);
ALTER TABLE public.order_details ADD CONSTRAINT FK_order_details__product_id FOREIGN KEY (product_id) REFERENCES public.products(id);
ALTER TABLE public.orders ADD CONSTRAINT FK_orders__business_id FOREIGN KEY (business_id) REFERENCES public.businesses(id);
ALTER TABLE public.orders ADD CONSTRAINT FK_orders__customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id);
ALTER TABLE public.orders ADD CONSTRAINT FK_orders__payment_method_id FOREIGN KEY (payment_method_id) REFERENCES public.payment_methods(id);
ALTER TABLE public.payment_methods ADD CONSTRAINT FK_payment_methods__business_id FOREIGN KEY (business_id) REFERENCES public.businesses(id);
ALTER TABLE public.shopping_carts ADD CONSTRAINT FK_shopping_carts__business_id FOREIGN KEY (business_id) REFERENCES public.businesses(id);
ALTER TABLE public.shopping_carts ADD CONSTRAINT FK_shopping_carts__customer_id FOREIGN KEY (customer_id) REFERENCES public.customers(id);